# Generated by Django 3.2.8 on 2021-10-27 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='controle',
            name='Data_Envio',
            field=models.DateField(blank=True, null=True, verbose_name='data'),
        ),
    ]
